#!/bin/bash

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_2 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/marzieh_kermany_vit/vit.pth.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_2 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/marzieh_kermany_vit/vit.pth.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_2 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/marzieh_kermany_vit/vit.pth.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_1/fold_2/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb

#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_1 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb
#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_1 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb
#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_1 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_1/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_1/fold_1/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_1/fold_2/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb


#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --norm
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_4 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb 

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_5 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --loss=cross_entropy

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_6 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --loss=focal --norm
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_7 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-2 --warmup_epochs=10 --lr=1e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --loss=emd --norm

#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --norm --norm_pix_loss --in_ch=1
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_23 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=50 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=5e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=emd --norm --in_ch=1
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_24 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=emd --norm --in_ch=1
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_25 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=1
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_26 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=1

# Avg 0,35395
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_34 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=1 --us 
#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --norm --norm_pix_loss --in_ch=1
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_34 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_1/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=1 --us 
#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=1.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --norm --norm_pix_loss --in_ch=1
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_34 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_2/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=1 --us
#python eval.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_34 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --backbone=vit_base_patch16 --n_cl=3 --in_ch=1 --norm --global_pool

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_35 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=3 --us 
#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --norm
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_35 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_1/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=3 --us 
#python 25D_mae.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --epochs=800 --batch_size=256 --optim=AdamW --wd=1e-2 --lw=10 --warmup_epochs=20 --lr=3e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.95 --n_cl=3 --in_ch=3 --exclude_nb --norm
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_35 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_2/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=3 --us
#python eval.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_35 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --backbone=vit_base_patch16 --n_cl=3 --in_ch=3 --norm --global_pool


#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_36 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=1 --us 
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_36 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_1/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=1 --us 
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_36 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_2/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=1 --us
#python eval.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_36 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --backbone=vit_base_patch16 --n_cl=3 --in_ch=1 --norm --global_pool

python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_47 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=40 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=1 --us 
python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_47 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_1/epoch_800.tar --epochs=40 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=1 --us 
python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_47 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_2/epoch_800.tar --epochs=40 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=1 --us
python eval.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_47 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --backbone=vit_base_patch16 --n_cl=3 --in_ch=1 --norm --global_pool


#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_37 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/saved_models/SSL/retfound/RETFound_oct_weights.pth --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=3 --us 
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_37 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/saved_models/SSL/retfound/RETFound_oct_weights.pth --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=3 --us 
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_37 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/saved_models/SSL/retfound/RETFound_oct_weights.pth --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=focalemd --norm --in_ch=3 --us
#python eval.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_37 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --backbone=vit_base_patch16 --n_cl=3 --in_ch=3 --norm --global_pool

#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_38 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_0/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=3 --us 
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_38 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_1/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=3 --us 
#python train_vit_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_38 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_2/fold_2/epoch_800.tar --epochs=200 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=crossemd --norm --in_ch=3 --us
#python eval.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_38 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --backbone=vit_base_patch16 --n_cl=3 --in_ch=3 --norm --global_pool

#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_40 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us 
#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_40 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=1 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_1/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us 
#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_40 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=2 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_2/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us 
#python eval_hier.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_40 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --n_cl=3 --in_ch=1 --norm --global_pool

#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_41 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us 

#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_42 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-3 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us

#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_43 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-3 --warmup_epochs=10 --lr=2.5e-5 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us

#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_44 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=focal --norm --in_ch=1 --us

#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_45 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=2.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.95 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us 

#python train_hierarch_bscan.py --save_dir=/msc/home/temree86/project/src/itsamemario/saved_models/experiment_46 --data_dir=/msc/home/temree86/project/data/MARIO-Challenge/data_2/ --fold=0 --pretrained --pretrained_model=/msc/home/temree86/project/src/itsamemario/saved_models/SSL/mae/experiment_3/fold_0/epoch_800.tar --epochs=100 --batch_size=64 --optim=AdamW --wd=1e-6 --warmup_epochs=10 --lr=7.5e-4 --backbone=mae_vit_base_patch16 --grad_norm_clip=2.0 --global_pool --beta2=0.999 --n_cl=3 --exclude_nb --loss=cross_entropy --norm --in_ch=1 --us 
